### ISSUE TITLE
Invalid format in gap warning

### ISSUE THREAD

**Issue by Julius-Bendt** [Julius-Bendt/tid.jub.dk#35]
![image](https://github.com/Julius-Bendt/tid.jub.dk/assets/22844949/c3a6b71a-ccfd-4509-bb41-642690a7dabf)

```
0800-0815: A - A
0815-0915: B - B
0915-0930: C - C
0930-0945: D - D
1000-1115: E - E
1130-1230: E
1230-1400: C
```

**Comment by Neophear** [comment]
0700-0715: A - Something A
0715-0745: B - Something B
0800-0915: B
1000-1015: B
1015-1115: C - Something C
1115-1130: B
1145-1200: B
1230-1245: B
1245-1315: C
1315-1330: A
1330-1500: C
1630-1645: D - Something D
1900-2015: C
